print("hello \"world\" world")
print('I\'m Riyaz')
print("line A\nLine B\nLine C")
print("Sr.No.\t Name\t \t Class")
print("this is backslash \\")
print("This is double backslash \\\\")
print("this last char eater\bh")
